import 'package:flutter/material.dart';

import '../theme/app_theme.dart';

/// Shows the real video poster frame (`reel.thumbnailUrl`, generated by the
/// backend on upload) as a grid-cell background, falling back to a gradient
/// when the reel has no thumbnail yet or the image fails to load.
class ReelThumbnail extends StatelessWidget {
  const ReelThumbnail({
    super.key,
    required this.thumbnailUrl,
    this.fallbackGradient = const [AppColors.surface2, AppColors.bg],
  });

  final String? thumbnailUrl;
  final List<Color> fallbackGradient;

  @override
  Widget build(BuildContext context) {
    final url = thumbnailUrl;
    if (url == null || url.isEmpty) return _Fallback(gradient: fallbackGradient);
    return Image.network(
      url,
      fit: BoxFit.cover,
      width: double.infinity,
      height: double.infinity,
      errorBuilder: (_, __, ___) => _Fallback(gradient: fallbackGradient),
    );
  }
}

class _Fallback extends StatelessWidget {
  const _Fallback({required this.gradient});

  final List<Color> gradient;

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: gradient,
        ),
      ),
      child: Center(
        child: Icon(
          Icons.play_circle_fill_rounded,
          color: Colors.white.withValues(alpha: 0.35),
          size: 36,
        ),
      ),
    );
  }
}
